version: '3.9'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    env_file:
      - ../server/.env.example
    ports:
      - '8080:8080'
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    ports:
      - '4173:80'
    depends_on:
      - api
